# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: "/#about"
    weight: 1
  - name: People
    url: "/#people"
    weight: 2
    id: People
  - name: Projects
    url: "/#projects"
    weight: 3
  - name: Publications
    url: "/publication"
    weight: 4
  - name: Handbook
    url: "https://lnn-ucph.github.io/LNN-UCPH-Handbook/"
    weight: 5


